[build]
  command = "npm run build"  # Your build command here
  publish = "/opt/build/repo/build"  # Your publish directory here
  ignore_warnings = true  # This line tells Netlify to ignore warnings
